const projects = {

  projectList: [
    {
      id: 'skyfall',
      previewId: 'project-preview',
      title: 'Skyfall',
      client: 'Orange Customer',
      description: 'This is the description of the project. Here, Celia will put a lot of text because she like to write a lot of shit. Love you babe <3.',
      date: '2016',
      team: 'Lei Xing<br/>Jantana Hennard<br/>Maximilien Jourdain<br/>Tonny Houziaux',
      role: 'Art Direction<br/>Conceptor<br/>Illustrator<br/>Motion Designer',
      reward: 'Award 2016 Design for all of the Orange young designer competition',
      pictures: [
        'picture-skyfall-0',
        'picture-skyfall-1',
        'picture-skyfall-2',
        'picture-skyfall-3',
      ],
      color: 'rgb(255, 200, 107)',
    },
    {
      id: 'fuse',
      previewId: 'project-preview',
      title: 'Fuse',
      client: 'Orange Customer',
      description: 'This is the description of the project. Here, Celia will put a lot of text because she like to write a lot of shit. Love you babe <3.',
      date: '2016',
      team: 'Lei Xing<br/>Jantana Hennard<br/>Maximilien Jourdain<br/>Tonny Houziaux',
      role: 'Art Direction<br/>Conceptor<br/>Illustrator<br/>Motion Designer',
      reward: 'Award 2016 Design for all of the Orange young designer competition',
      pictures: [
        'picture-skyfall-0',
        'picture-skyfall-1',
        'picture-skyfall-2',
        'picture-skyfall-3',
      ],
      color: 'rgb(107, 255, 215)',
    },
    {
      id: 'orange',
      previewId: 'project-preview',
      title: 'Parcea',
      client: 'Orange Customer',
      description: 'This is the description of the project. Here, Celia will put a lot of text because she like to write a lot of shit. Love you babe <3.',
      date: '2016',
      team: 'Lei Xing<br/>Jantana Hennard<br/>Maximilien Jourdain<br/>Tonny Houziaux',
      role: 'Art Direction<br/>Conceptor<br/>Illustrator<br/>Motion Designer',
      reward: 'Award 2016 Design for all of the Orange young designer competition',
      pictures: [
        'picture-skyfall-0',
        'picture-skyfall-1',
        'picture-skyfall-2',
        'picture-skyfall-3',
      ],
      color: 'rgb(129, 107, 255)',
    },
    {
      id: 'retrograph',
      previewId: 'project-preview',
      title: 'Retrograph',
      client: 'Orange Customer',
      description: 'This is the description of the project. Here, Celia will put a lot of text because she like to write a lot of shit. Love you babe <3.',
      date: '2016',
      team: 'Lei Xing<br/>Jantana Hennard<br/>Maximilien Jourdain<br/>Tonny Houziaux',
      role: 'Art Direction<br/>Conceptor<br/>Illustrator<br/>Motion Designer',
      reward: 'Award 2016 Design for all of the Orange young designer competition',
      pictures: [
        'picture-skyfall-0',
        'picture-skyfall-1',
        'picture-skyfall-2',
        'picture-skyfall-3',
      ],
      color: 'rgb(255, 0, 0)',
    },
  ],
};

module.exports = projects;
