const projects = {

  projectList: [
    {
      id: 'parcea',
      previewId: 'project-preview',
      title: 'Parcea',
      description: 'Arduino project at Gobelins’s school. We did a real object with cardboards and 3D printing. The mechanism is controlled by small motors and an Arduino.',
      client: '',
      pitch: 'Parcea is a smart object connected in real time to your last shipment that will give you updates with a visual notification at each step of the delivery.',
      date: '2016',
      team: '<a href="http://anaisiris.com/" target="_blank">Anaïs Lefebvre</a><br/><a href=" http://kirgansomville.com" target="_blank">Kirgan Somville</a><br/><a href="https://twitter.com/JSinnay" target="_blank">Yannis Jonckierre</a>',
      role: 'Conceptor<br/>UI / UX<br/>3D',
      reward: '',
      url: '',
      urlText: '',
      medias: [
        { id: 'parcea-media-0', type: 'image' },
        { id: 'parcea-media-1', type: 'image' },
        { id: 'parcea-media-2', type: 'image' },
        { id: 'parcea-media-3', type: 'image' },
        { id: 'parcea-media-4', type: 'image' },
        { id: 'parcea-media-5', type: 'image' },
      ],
      color: 'rgb(208, 199, 190)',
    },
    {
      id: 'daphne',
      previewId: 'project-preview',
      title: 'Daphné',
      description: 'Side project made with love.',
      client: 'Daphné',
      pitch: 'Daphné Launay is a photograph based at Paris. This is her portfolio where you can find some of her realizations.',
      date: '2018',
      team: '<a href="https://twitter.com/anthelme_dumont" target="_blank">Anthelme Dumont</a><br/><a href="https://twitter.com/DaphneLeaunait" target="_blank">Daphnée Launey</a>',
      role: 'Art Director<br/>UI / UX',
      reward: '',
      url: '',
      urlText: '',
      medias: [
        { id: 'daphne-media-0', type: 'image' },
        { file: 'media-1', type: 'video' },
        { id: 'daphne-media-2', type: 'image' },
        { id: 'daphne-media-3', type: 'image' },
        { id: 'daphne-media-4', type: 'image' },
      ],
      color: 'rgb(205, 175, 165)',
    },
    {
      id: 'orange',
      previewId: 'project-preview',
      title: 'Orange',
      description: 'Orange Designers competition - "Design for all" reward (open to students and young graduated). Orange social customer is a cool and fun after-sale services invented for Orange.',
      client: 'Orange',
      pitch: 'The customer service is founded on a game inside of the operator community : the victims and the saviors. With Orange Social Customer, the operator manages the service while knowing how to fade when "saviors" and "victims" find, together, a solution.',
      date: '2016',
      team: '<a href="http://www.leixing.fr" target="_blank">Lei Xing</a>',
      role: 'Conceptor<br/>Art Director<br/>Motion & Illustration',
      reward: '',
      url: 'https://vimeo.com/176373915',
      urlText: 'See the video',
      medias: [
        { id: 'orange-media-0', type: 'image' },
        { file: 'media-1', type: 'video' },
        { file: 'media-2', type: 'video' },
        { file: 'media-3', type: 'video' },
        { file: 'media-4', type: 'video' },
      ],
      color: 'rgb(229, 206, 183)',
    },
    {
      id: 'fuse',
      previewId: 'project-preview',
      title: 'Fuse',
      description: 'Gobelins School WebGL Project. Multiplayer experience website.',
      client: 'Orange Customer',
      pitch: 'We wanted to design an alternative way of creating Art with people, making it accessible to everybody, even without any artistic abilities. Give the chance to expose a virtual gallery.',
      date: '2018',
      team: '<a href="http://anaisiris.com/" target="_blank">Anaïs Lefebvre</a><br/><a href="http://steviaplease.me" target="_blank">Camille Frairrot</a><br/><a href="https://jackyfong.com" target="_blank">Jacky Fong</a><br/><a href="https://twitter.com/anthelme_dumont" target="_blank">Anthelme Dumont</a>',
      role: 'Art Director<br/>UI / UX',
      reward: '',
      url: 'https://www.behance.net/gallery/54737151/Fuse-WebGL-Experience',
      urlText: 'Visit the Behance',
      medias: [
        { id: 'fuse-media-0', type: 'image' },
        { file: 'media-1', type: 'video' },
        { file: 'media-2', type: 'video' },
        { file: 'media-3', type: 'video' },
        { file: 'media-4', type: 'video' },
      ],
      color: 'rgb(222, 224, 223)',
    },
    {
      id: 'skyfall',
      previewId: 'project-preview',
      title: 'Skyfall',
      description: 'Side project for the DDD 2017 OFF Milano. Monogrid gave us the opportunity to be part of the Devexperiments.',
      client: '',
      pitch: 'We decided to create an emotional experiment based on the Skyfall music.',
      date: '2017',
      team: '<a href="https://twitter.com/MathisBiabiany" target="_blank">Mathis Biabiany</a>',
      role: 'Conceptor<br/>Art Director<br/>3D',
      reward: '',
      url: 'http://devx.ddd.it/en/experiment/23',
      urlText: 'Visit the website',
      medias: [
        { id: 'skyfall-media-0', type: 'image' },
        { file: 'media-1', type: 'video' },
        { id: 'skyfall-media-2', type: 'image' },
        { id: 'skyfall-media-3', type: 'image' },
      ],
      color: 'rgb(217, 221, 245)',
    },
  ],
};

module.exports = projects;
