const projects = {

  projectList: [
    {
      id: 'skyfall',
      previewId: 'project-preview',
      title: 'Skyfall',
      description: 'Bla bla bla blaaaaaaah',
      client: 'Orange Customer',
      pitch: 'This is the description of the project. Here, Celia will put a lot of text because she like to write a lot of shit. Love you babe <3.',
      date: '2016',
      team: 'Lei Xing<br/>Jantana Hennard<br/>Maximilien Jourdain<br/>Tonny Houziaux',
      role: 'Art Direction<br/>Conceptor<br/>Illustrator<br/>Motion Designer',
      reward: 'Award 2016 Design for all of the Orange young designer competition',
      medias: [
        { id: 'picture-skyfall-0', type: 'image' },
        { id: 'picture-skyfall-1', type: 'image' },
        { id: 'picture-skyfall-2', type: 'image' },
        { id: 'picture-skyfall-3', type: 'image' },
        { id: 'test', type: 'video' },
      ],
      color: 'rgb(245, 231, 218)',
    },
    {
      id: 'fuse',
      previewId: 'project-preview',
      title: 'Fuse',
      description: 'Bla bla bla blaaaaaaah',
      client: 'Orange Customer',
      pitch: 'This is the description of the project. Here, Celia will put a lot of text because she like to write a lot of shit. Love you babe <3.',
      date: '2016',
      team: 'Lei Xing<br/>Jantana Hennard<br/>Maximilien Jourdain<br/>Tonny Houziaux',
      role: 'Art Direction<br/>Conceptor<br/>Illustrator<br/>Motion Designer',
      reward: 'Award 2016 Design for all of the Orange young designer competition',
      medias: [
        { id: 'picture-skyfall-0', type: 'image' },
        { id: 'picture-skyfall-1', type: 'image' },
        { id: 'picture-skyfall-2', type: 'image' },
        { id: 'picture-skyfall-3', type: 'image' },
        { id: 'test', type: 'video' },
      ],
      color: 'rgb(245, 231, 218)',
    },
    {
      id: 'orange',
      previewId: 'project-preview',
      title: 'Parcea',
      description: 'Bla bla bla blaaaaaaah',
      client: 'Orange Customer',
      pitch: 'This is the description of the project. Here, Celia will put a lot of text because she like to write a lot of shit. Love you babe <3.',
      date: '2016',
      team: 'Lei Xing<br/>Jantana Hennard<br/>Maximilien Jourdain<br/>Tonny Houziaux',
      role: 'Art Direction<br/>Conceptor<br/>Illustrator<br/>Motion Designer',
      reward: 'Award 2016 Design for all of the Orange young designer competition',
      medias: [
        { id: 'picture-skyfall-0', type: 'image' },
        { id: 'picture-skyfall-1', type: 'image' },
        { id: 'picture-skyfall-2', type: 'image' },
        { id: 'picture-skyfall-3', type: 'image' },
        { id: 'test', type: 'video' },
      ],
      color: 'rgb(245, 231, 218)',
    },
    {
      id: 'retrograph',
      previewId: 'project-preview',
      title: 'Retrograph',
      description: 'Bla bla bla blaaaaaaah',
      client: 'Orange Customer',
      pitch: 'This is the description of the project. Here, Celia will put a lot of text because she like to write a lot of shit. Love you babe <3.',
      date: '2016',
      team: 'Lei Xing<br/>Jantana Hennard<br/>Maximilien Jourdain<br/>Tonny Houziaux',
      role: 'Art Direction<br/>Conceptor<br/>Illustrator<br/>Motion Designer',
      reward: 'Award 2016 Design for all of the Orange young designer competition',
      medias: [
        { id: 'picture-skyfall-0', type: 'image' },
        { id: 'picture-skyfall-1', type: 'image' },
        { id: 'picture-skyfall-2', type: 'image' },
        { id: 'picture-skyfall-3', type: 'image' },
        { id: 'test', type: 'video' },
      ],
      color: 'rgb(245, 231, 218)',
    },
  ],
};

module.exports = projects;
